import type { Metadata } from "next";

import "./globals.css";
import { DM_Sans } from "next/font/google";

const font = DM_Sans({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-primaryBackground`}>
        {children}
      </body>
    </html>
  );
}
